### ISSUE TITLE
@Requires in usual iPOJO component does not work

### ISSUE THREAD

**Issue by sauthieg** [wisdom-framework/wisdom#280]
I've got a simple iPOJO component like the following.
At first, I tried to have some other services (iPOJO ones too) injected using `@Requires`, but the dependency was never injected, and I got NPE. Strangely, this works well if I change my `@Requires` with a `@Bind` on a setter ...

``` java
@Component
@Provides
@Instantiate
public class MapPasteService implements PasteService {
    @Requires
    private HashService hashService;
}

**Comment by cescoffier** [comment]
Let's close it. Please reopen if needed.
