### ISSUE TITLE
Distinguish HTTPs and HTTPs Mutual Authentication ports

### ISSUE THREAD

**Issue by obigard** [wisdom-framework/wisdom#332]

**Comment by cescoffier** [comment]
I think this is going to be part of a broader refactoring:

* Allow the definition of any number of http(s) server each one with its own configuration.
* Servers would be configured as follows:

````
ssl: true | false
authentication: true|false
port: -1, 0, integer
allow: array of path regex that should be allowed
deny: array of route regex that are not allowed
onDenied: path for redirection
````

To serve a request a path must match the 'allow' clause and not match the 'deny' clause.

**Comment by cescoffier** [comment]
Part of #462
