### ISSUE TITLE
Study Redis, Hazelcast, JGroups, ...

### ISSUE THREAD

**Issue by obigard** [wisdom-framework/wisdom#338]

**Comment by cescoffier** [comment]
Hazelcast is handled by #419.

**Comment by barjo** [comment]
The issue/question is too broad, I will close it.

**Comment by cescoffier** [comment]
Hazelcast has been covered (see clustering).

On 24 juillet 2015 at 05:50:24, Jonathan Bardin (notifications@github.com) wrote:

Closed #338.
