### ISSUE TITLE
Some critical error should also be added to the wisdom.log file

### ISSUE THREAD

**Issue by evrignaud** [wisdom-framework/wisdom#348]
When Wisdom prints errors in the Shelby console it can be difficult to figure out what's wrong, because the console is full to logs.
It may help if the errors were also added into the wisdom.log file.

For exemple, when the web server is down due to a REST method that does not return a Result, it's very difficult to diagnose, because the console is full with a big mess and the log file contain only INFO messages.

**Comment by cescoffier** [comment]
The default logger configuration can be customized to reduce the number of entries, or to redirect some of the entries to another appender. For instance, in your case, you can just use another appender as described done in:
https://gist.github.com/cescoffier/dfb6ecac2268872a9411
