### ISSUE TITLE
Replace Akka by a Thread Pool / Executor service

### ISSUE THREAD

**Issue by cescoffier** [wisdom-framework/wisdom#398]
Initially I decided to use Akka for its actor model. But after some time I realize I'm using it as a pure thread pool. It's a big big for a thread pool (as it requires Scala).

We should replace it by a better thread pool service, maybe using Quartz (http://quartz-scheduler.org/generated/2.2.1/html/qs-all/#page/Quartz_Scheduler_Documentation_Set%2Fco-abt_quartz_features.html%23) or pure Executors.

**Comment by remi-parain** [comment]
I use the akka service when i need the scheduled behavior for a non-harcoded time interval ( no annotation ). Will it be possible to do this with Thread Pool or will it need the extension?

**Comment by cescoffier** [comment]
The service will be a bit different, but you will have this feature, in a more flexible way actually. 

If you rely on Akka API, you would need to deploy the (current) Akka-System explicitly.

**Comment by cescoffier** [comment]
Ongoing work on the #398 branch.

**Comment by cescoffier** [comment]
Right now, we still provide Akka (in the 0.7.1), Akka will be moved as an extension in the 0.7.2

**Comment by cescoffier** [comment]
So, I've made an implementation of executors and schedulers based on the Java Execution Services. This implementation is close to the JavaEE Concurrent specification (so you may recognize some concepts), but is definitely not an implementation (as it's really close to JavaEE).

I've migrated all Wisdom core feature to the new model.
