### ISSUE TITLE
Add section inside conf file ?

### ISSUE THREAD

**Issue by hboumedane** [wisdom-framework/wisdom#405]
Hello,

Is it possible to add section for conf file , so we can have for example different kind of properties :
properties for dev, production and so on ...
this will allow for example to load properties depending on the type of application mode (dev, stage, production)....

**Comment by cescoffier** [comment]
Hi,

Yes and No.

There is no direct support for this, **but** there is a parameter to indicate which configuration file you want: `-Dapplication.configuration=PATH`.

As with the 0.7.0 configuration files supports `includes`, you should be able to have what you need pretty quickly.

**Comment by hboumedane** [comment]
yes, but with include I need to specify inside my code wich kind of properties I will use depending on the application mode ?

**Comment by cescoffier** [comment]
What about a test.conf like this:

```
include application.conf
# Add you overridden value here 
````

**Comment by hboumedane** [comment]
great, thank you
