### ISSUE TITLE
Use swagger (or other API documentation tool) with wisdom

### ISSUE THREAD

**Issue by vcavel** [wisdom-framework/wisdom#412]
Swagger is a really neat tool to generate a very nice interactive documentation for a REST API. It's fairly easy to integrate with JAX-RS, it automatically generates and serves your documentation, it is really really cool!

I am having the hardest time to integrate it with wisdom framework though, there is a project (https://github.com/livingobjects/wisdom-swagger) that aims at simplifying things but it seems that it will only serve the swagger documentation that you need to previously write, which is not ideal!

**First question :** Does anyone have had any success using swagger with wisdom?
**Second question :** Does anyone have had any success in using some  tool that generates a nicer documentation than the javadoc and make it play nicely with wisdom, a swagger equivalent?

If those 2 questions get a "no" answer, wouldn't it be super amazing to have a fully automatic generation of a swagger documentation for the REST APIs that we make using wisdom? That would be a super nice feature no?

Swagger's demo : http://petstore.swagger.wordnik.com/#!/pet

**Comment by cescoffier** [comment]
Hi,

I really like the idea. I did a first study to understand how we can populate Swagger metadata from the metadata Wisdom keep. It's not straightforward but possible.

About something equivalent to Swagger, I've tried a couple of things, but Swagger is definitely the most advanced, and flexible. However, it miss a couple of features:

* most of these tools are "RESTful-ish"-ed, which is nice but not always sufficient. This leads to the two next points:
* no support for Web socket - no description of the event and so on
* no RPC support (even if it's not hype to do RPC today, it's still there)
* Swagger is not easy to understand (well you may have seen this)


And to answer to your last question, Yes, having Swagger support would be just awesome. 

PS: I was not able to build your code, some dependencies were missing.

**Comment by vcavel** [comment]
For the websockets issue, it might be possible to use the annotation syntax of swagger (https://github.com/swagger-api/swagger-core/wiki/Annotations) to annotate the web socket services themselves. If the architecture of the websockets project is made correctly you should have well separated services and methods for every websocket calls (getUser, saveUser, ...), so annotating those would be fairly developer friendly! 

I honestly have no idea on how to make it play nicely with wisdom, I'm just throwing it in there!

I did not provide any code that was mine, the wisdom-swagger project is something I found on github, I didn't take part in it!

**Comment by cescoffier** [comment]
Hi,

Oh sorry about the mistakes. I was thinking you did the wisdom-swagger extension. 

About the web sockets, yes we should be able to massage Swagger to get something. 

are you going to have a look into this ?

**Comment by vcavel** [comment]
Hi Clément,

I'm not really planning on it, it doesn't sound like a minor task (at all) and I don't think that I can give it the time it deserves, sorry!

Let's leave that pending for now and hope that a good soul wants to help or that I can make time for it in the future!

**Comment by barjo** [comment]
Hi, 

I will try to have a look at it, but It may takes quite some time.

**Comment by cescoffier** [comment]
Cool !

We should first design a battle plan, I probably will help

**Comment by cescoffier** [comment]
@barjo is looking at RAML.

**Comment by cescoffier** [comment]
For information, here is @barjo work: https://github.com/barjo/wisdom-raml

It's already in a nice shape.

**Comment by barjo** [comment]
The project has been moved into the extensions https://github.com/wisdom-framework/wisdom/tree/master/extensions/wisdom-raml. Feel free to give it a try :eyes:
