### ISSUE TITLE
Support the OpenUI5 JavaScript UI library

### ISSUE THREAD

**Issue by Adanz** [wisdom-framework/wisdom#413]
OpenUI5 is an Open Source JavaScript UI library. https://github.com/SAP/openui5/

thanks!

**Comment by cescoffier** [comment]
What do you mean by support ? (Sorry I don't know OpenUI5).

**Comment by Adanz** [comment]
OpenUI5(https://github.com/SAP/openui5/) base JQuery, May be there is support .
but not found any example.

**Comment by cescoffier** [comment]
It seems to be available as a webjars, so just add this dependency to your project:

```
<dependency>
    <groupId>org.webjars</groupId>
    <artifactId>openui5</artifactId>
    <version>1.24.2</version>
</dependency>
```

and then import the scripts:

```
<script id="sap-ui-bootstrap"
   src="libs/sap-ui-core.js"
   data-sap-ui-theme="sap_bluecrystal"
   data-sap-ui-libs="sap.m">
</script>
```

and that's all...

**Comment by Adanz** [comment]
thanks, I will test.

**Comment by cescoffier** [comment]
Any feedback ? 
Please reopen the issue, if you have an issue.
