### ISSUE TITLE
add new sensor to monitor dashboard

### ISSUE THREAD

**Issue by hboumedane** [wisdom-framework/wisdom#415]
Hello,

Is it possible to add a sensor for monitoring JDBC pool connection (or datasources) inside the dashboard ?

**Comment by cescoffier** [comment]
Yes, you just have to register a health check service (http://wisdom-framework.org/documentation/apidocs/0.7.0/org/wisdom/monitor/service/HealthCheck.html)

**Comment by hboumedane** [comment]
yes, but what i need is some helpful information such (number of open connections, number of connections in the pool).
For exemple, you can create MBean interface for that which we can use to get this information about the jdbc database connection.
The healthcheck don't allow such things.

**Comment by cescoffier** [comment]
Oh, I see, in that case you should create an extension. It won’t be on the dashboard but on another page. 

We could also look into a way to extend the dashboard page, with the risk to get a really bloated page.


On 16 janvier 2015 at 10:27:11, hboumedane (notifications@github.com) wrote:

yes, but what i need is some helpful information such (number of open connections, number of connections in the pool).
For exemple, you can create MBean interface for that which we can use to get this information about the jdbc database connection.
The healthcheck don't allow such things.

**Comment by hboumedane** [comment]
yes, an extension is a good idea.
for the info, i was trying to use this code to monitor bonecp pool connection: 
'''java
public String getConnectionStatus() {
    String status = "unknown";
    if (dataSource instanceof BoneCPDataSource) {

        BoneCPDataSource bcpDataSource = (BoneCPDataSource) dataSource;
        BoneCP bcp = bcpDataSource.getPool();
        status = "JDBC connections: " + bcp.getTotalLeased()
            + " in use / " + bcp.getTotalFree()
            + " in pool / total created "
            + bcp.getTotalCreatedConnections();

    }
    return status;
}
'''
and i noticed that bonecp depends on guava version 15.0 but wisdom uses guava 18.0 , any way maybe it's time to change jdbc pool implentation because bonecp is no more updated..

**Comment by cescoffier** [comment]
* About the guava version, that's why we wrapped BoneCP. 
* About a new pool, definitely. I'm looking at HikariCP.
