### ISSUE TITLE
Update to Vertx 3.x

### ISSUE THREAD

**Issue by cescoffier** [wisdom-framework/wisdom#417]
Vertx 3.x should be available soon. We should switch once the GA is announced.

**Comment by vietj** [comment]
yes :)

**Comment by cescoffier** [comment]
@vietj an idea of the official release date ?

**Comment by vietj** [comment]
you can expect in the first quarter of this year, we have done a couple of milestones so far

**Comment by mehdi-d** [comment]
any news about this enhancement?

**Comment by cescoffier** [comment]
Not much. I’ve made a prototype to see how things can work. Well it does, but there are still a lot of work to be done before being ready.

On 21 septembre 2015 at 21:23:58, Elmehdi Damou (notifications@github.com) wrote:

any news about this enhancement?

**Comment by cescoffier** [comment]
I gonna push wisodm 0.10.0-SNAPSHOT later today relying on vertx-core 3.1.0

**Comment by cescoffier** [comment]
This has been done.
