### ISSUE TITLE
Expose the Vertx Event Bus a service

### ISSUE THREAD

**Issue by cescoffier** [wisdom-framework/wisdom#418]
By exposing the Vertx Event Bus as an OSGi service we allow applications to register themselves on the event bus and to interact using the event bus.

This would enable clustering.

**Comment by vietj** [comment]
more importantly it allows integration with async services.

**Comment by cescoffier** [comment]
IT's a first step, but yes, integration with the async services would be really great.

**Comment by vietj** [comment]
Vert.x 3 comes with proxies in front of the event bus, you should be able to inject them instead of using the event bus directly : https://github.com/vert-x3/vertx-service-proxy

At the moment we do have it for MongoDB.

**Comment by cescoffier** [comment]
Yes I saw that and it's great.

It will let us integrate these 'async' services in the OSGi service registry. 

BTW, in Vert.x 3 any way to inject our own ClusterManager instance (because it's the pain in the ass for us in Vert.x 2 ;-))

**Comment by vietj** [comment]
is ClusterManager a replacement for Vert.x cluster integration whose default is based on Hazelcast ?

**Comment by cescoffier** [comment]
In Vertx 2.x, there is a ClusterManagerFactory creating an instance of ClusterManager. The "default" is based on Hazelcast.

You have the choice between:
* giving the class name of the ClusterManagerFactory to use
* using a SPI file

None of these choices is really suitable for us.  It would be really nice we we can just provide the instance of ClusterManager (or ClusterManagerFactory) to use, so we can benefit from the Wisdom services.

**Comment by vietj** [comment]
Vert.x 3 has a create method that uses a VertxOptions object that can be configured with a ClusterManager instance.

~~~
VertxOptions options = new VertxOptions().setHAEnabled(true).setQuorumSize(quorumSize).setHAGroup(haGroup).setClustered(true).setClusterHost("localhost").setClusterManager(getClusterManager());
Vertx.clusteredVertx(options);
~~~

**Comment by cescoffier** [comment]
Great ! Exactly what we need !

PS: Any way to update it dynamically ;-)
