### ISSUE TITLE
Java 8 test compilation

### ISSUE THREAD

**Issue by Kricket** [wisdom-framework/wisdom#430]
Using wisdom:run, it doesn't appear to be possible to run tests using Java 8.

I have a unit test with a lambda expression in the test code. When I do wisdom:run, it won't compile since the -source for the compiler is 1.7.

So, I added the following to my pom:
```xml
	<build>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.2</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
					<testSource>1.8</testSource>
					<testTarget>1.8</testTarget>
				</configuration>
			</plugin>
```

The error then becomes:

> [ERROR] Failed to execute goal org.wisdom-framework:wisdom-maven-plugin:0.7.0:compile (default-compile) on project kpitv: Unable to execute mojo: Unable to parse configuration of mojo org.apache.maven.plugins:maven-compiler-plugin:3.2:compile for parameter testSource: Cannot find 'testSource' in class org.apache.maven.plugin.compiler.CompilerMojo -> [Help 1]

Using the properties of the POM doesn't work either [like shown here](http://stackoverflow.com/questions/10604007/maven-compiling-and-testing-on-different-source-levels).

**Comment by cescoffier** [comment]
Definitely a bug, gonna have a look

**Comment by cescoffier** [comment]
Here is a turn around:

```
<plugin>
    <artifactId>maven-compiler-plugin</artifactId>
    <executions>
        <execution>
            <id>default-testCompile</id>
            <goals>
                <goal>testCompile</goal>
            </goals>
            <configuration>
                <testSource>1.8</testSource>
                <testTarget>1.8</testTarget>
            </configuration>
        </execution>
    </executions>
    <configuration>
        <source>1.8</source>
        <target>1.8</target>
    </configuration>
</plugin>
```

**Comment by cescoffier** [comment]
Close issue as a turn around have been provided.
