### ISSUE TITLE
SunCertPathBuilderException: unable to find valid certification path to requested target !!

### ISSUE THREAD

**Issue by hboumedane** [wisdom-framework/wisdom#442]
Hi,
I have a wisdom server that serve https with self signed certificats (keystore.jks file).
when i try to access from application the server i get this exception : 
```java
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

```

**Comment by cescoffier** [comment]
Answer is there: https://groups.google.com/d/msg/wisdom-discuss/Qh2HGhcynZY/BwQ-KB9e1scJ

Please avoid cross-posting.

**Comment by hboumedane** [comment]
thanks for your help !!
