### ISSUE TITLE
how to tell wisdom to not filter files inside conf dir

### ISSUE THREAD

**Issue by hboumedane** [wisdom-framework/wisdom#445]
Hello,
 I have a jks file inside my conf directory ,  when i run wisdom the file is modified even when i use this : 
```maven
                    <nonFilteredExtensions>
                        <extension>jks</extension>
                    </nonFilteredExtensions>
```
so , how to prevent this from happening ??

**Comment by cescoffier** [comment]
Could you tell me which version of the wisdom plugin you are using and
where did you put the configuration. Check that the file has the .jks
extenstion (case matters here).

2015-02-18 15:51 GMT+01:00 hboumedane <notifications@github.com>:

**Comment by hboumedane** [comment]
i'm using 0.7.0 wisdom plugin version and yes my file nameis : keystore.jks

i put this config like that : 
```xml
            <plugin>
                <groupId>org.wisdom-framework</groupId>
                <artifactId>wisdom-maven-plugin</artifactId>
                <version>0.7.0</version>
                <extensions>true</extensions>
                <configuration>
                    <nonFilteredExtensions>
                        <extension>jks</extension>
                    </nonFilteredExtensions>
                </configuration>
            </plugin>
```

**Comment by cescoffier** [comment]
Seems to be a bug, gonna have a look. It's weird because we have an integration-test about this (as far as I remember).

**Comment by hboumedane** [comment]
you could add definitely the jks extension to NON_FILTERED_EXTENSIONS !!

**Comment by cescoffier** [comment]
Yes, but you should have been able to add it to the non filtered extension list (that's the bug).

**Comment by hboumedane** [comment]
indeed..

**Comment by cescoffier** [comment]
Found the bug, the configuration copy does not retrieve the `nonFilteredExtensions` parameter.

**Comment by cescoffier** [comment]
Two actions:

1. Add jks to the list of non-filtered extension
2. Add support for the `nonFilteredExtensions` parameter in the configuration copy

**Comment by hboumedane** [comment]
good job
