### ISSUE TITLE
iPOJOHelper is not compatible with wisdom 0.7.0 and 0.7.1-SNAPSHOT

### ISSUE THREAD

**Issue by barjo** [wisdom-framework/wisdom#446]
When running an it test that extends WisdomTest, 

```java
  helper = new IPOJOHelper(context);
  helper.isInstanceInvalid(OrientDbManagerComp.INSTANCE_NAME);
```
cause: 

`java.lang.ClassCastException: Cannot cast org.apache.felix.ipojo.handlers.architecture.ArchitectureHandler to org.apache.felix.ipojo.architecture.Architecture`

Furthermore, it seems that `getInstanceByName` return null value even if the instance is present.

**Comment by cescoffier** [comment]
I've found the issue. The helpers are loaded from the wrong classloader.
