### ISSUE TITLE
Only one Blackbox test can require the probe bundle

### ISSUE THREAD

**Issue by cescoffier** [wisdom-framework/wisdom#450]
The way we install and uninstall the probe (i.e. test bundle) in blackbox test does not work.

**Comment by cescoffier** [comment]
Unfortunately, the previous way to deploy the test/probe bundle was quite broken.

I've provided a new way, incompatible.

In your test classes, add:

```
    @BeforeClass
    public static void init() throws BundleException {
        installTestBundle();
    }

    @AfterClass
    public static void cleanup() throws BundleException {
        removeTestBundle();
    }
```

instead of the `deployTestBundle()` method (that has disappeared).

**Comment by agonist** [comment]
Okay good to now thank's for the quick fix. I'll try it after the release
