### ISSUE TITLE
Customize requests and results type

### ISSUE THREAD

**Issue by amischler** [wisdom-framework/wisdom#456]
In a similar fashion of the @Consumes and @Produces annotations of [java.ws.rs](https://docs.oracle.com/cd/E19776-01/820-4867/ghrpv/), it could be great to be able to :

 - route a request more precisely to a specific controller method based on the content type of the request
 - specify the type of the result that a controller method is able to send to the client

**Comment by amischler** [comment]
Link to the original discussion: https://groups.google.com/forum/#!topic/wisdom-discuss/QikTZFoIVds

**Comment by cescoffier** [comment]
We should not forget to write the `VARY` header in the response

**Comment by cescoffier** [comment]
Another detail that matters, it should return `NOT_ACCEPTABLE` when no methods can consume the given content (instead of `NOT_FOUND`)

**Comment by cescoffier** [comment]
Mime type range should be supported.
For reference: http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

**Comment by cescoffier** [comment]
After discussion, here are the planned format:

````
 @Route(method = HttpMethod.GET, uri = "/",
                    accepts = "text/plain",
                    produces = "application/html"
            )
public Result action() {
	// ...
}
````

It uses `accepts`` and not `consume`, as `accept` is a HTTP concept, while `consume` is not.

**Comment by amischler** [comment]
It could also be great to be able to specify multiple values for accepts and produces, e.g.:
```java
@Route(method = HttpMethod.GET, uri = "/",
                    accepts = "text/plain",
                    produces = "application/html,application/json"
            )
public Result action() {
    // ...
}
```

**Comment by cescoffier** [comment]
yes it's done that way - both attributes can receive several values. `Accepts` accepts wildcard such as `text/*`, while `produces` does not.

**Comment by cescoffier** [comment]
For information, I'm really close to get it done. Have to implement integration tests and update the documentation.

(was stuck on conflicts detection, but founds an acceptable algorithm)
