### ISSUE TITLE
@Body should allow Parametric Types for Json mapping

### ISSUE THREAD

**Issue by magnet** [wisdom-framework/wisdom#458]
Currently, using @Body on a parameter that has a generic type only provides the Jackson Mapper with the raw type.

e.g
public Result action(@Body Foo<Bar> foo) { }
// currently Jackson knows only about the raw type Foo

Generic type info should be passed to allow Jackson to use the right deserializers.

Right now the workaround is not to use the @Body annotation and use the Jackson mapper with the proper TypeReference or by constructing a JavaType.

**Comment by cescoffier** [comment]
How would you do that by default ? 

Would adding a parameter to body be acceptable ?

**Comment by cescoffier** [comment]
Here are two approaches:

1. Adding parameter to @Body:
It seems to be possible if we pass a list of class to `@Body`
For instance, you would be something like:

```
public Result action(@Body(String.class) Foo<String> foo) {
}
```

This would be the most reliable.

2. Inferring type
However, we may be able to retrieve the full type of the parameter as we do in the parameter converters. 

I definitely prefers the second approach, but I'm not sure it's (always) possible.

**Comment by magnet** [comment]
I'm not in favor of adding the type class in @Body. It wouldn't work well with multiple levels of parametric types.

The generic information is available at runtime for method parameters since Java 1.5 (it's the generic signature in the bytecode).

See Method#getGenericParameterTypes

I suggest only concrete types should be supported (not typevars).  Supporting typevars would make sense only in the case of generic controllers, but resolving the type gets tricky and it's really a corner case.

**Comment by cescoffier** [comment]
You are right, it seems to be possible. I'm working on it.

**Comment by cescoffier** [comment]
Done :-)

Check https://github.com/wisdom-framework/wisdom/blob/master/framework/integration-tests/src/main/java/controllers/generic/ControllerReceivingGenerics.java

**Comment by magnet** [comment]
Nice :)
Thanks for the quick fix!

**Comment by agjini** [comment]
Thanks Clément for your reactivity !
