### ISSUE TITLE
How does authentication work?

### ISSUE THREAD

**Issue by Kricket** [wisdom-framework/wisdom#462]
After reading the documentation, I see that it's possible to check that a "username" key has been defined in the Context in order to allow or deny access to a resource. However, there is nothing to indicate how this "username" got there.

Could the documentation be improved so that it provides a more complete explanation of how this might be used? How would a user log on/log off? How would a wisdom component check a password, and what would it do in the event of success/failure? Is the "context" something that a malicious user could hack, by injecting a random username?

**Comment by cescoffier** [comment]
Hello,



2015-03-31 13:40 GMT+02:00 Kricket <notifications@github.com>:

> After reading the documentation, I see that it's possible to check that a
> "username" key has been defined in the Context in order to allow or deny
> access to a resource. However, there is nothing to indicate how this
> "username" got there.
>
The username is set by an interceptor (
https://github.com/wisdom-framework/wisdom/blob/master/core/router/src/main/java/org/wisdom/router/security/AuthenticationInterceptor.java).
This filter looks for a Authenticator service to authenticate the user such
as the Monitor Authenticator (
https://github.com/wisdom-framework/wisdom/blob/master/extensions/wisdom-monitor/src/main/java/org/wisdom/monitor/extensions/security/MonitorAuthenticator.java).
The Context.getUserName is independent of the authentication mechanism, and
is just here to let controller retrieve it. It's not used to check whether
the request is authenticated or not.

Each authenticated action can define the name of the authenticator is want
to use. If this authenticator is not available, the action is rejected.


> Could the documentation be improved so that it provides a more complete
> explanation of how this might be used? How would a user log on/log off? How
> would a wisdom component check a password, and what would it do in the
> event of success/failure? Is the "context" something that a malicious user
> could hack, by injecting a random username?
>

About the documentation, definitely. The current documentation is quite
succinct (
http://wisdom-framework.org/reference/0.8.0/index.html#_authentication).

The user login / logoff is not directly defined by the authenticator (just
checking whether a user is authenticated). So you need a 'controller'
handling this in a way the authenticator can understand.

For instance, in
https://github.com/wisdom-framework/wisdom/blob/master/extensions/wisdom-monitor/src/main/java/org/wisdom/monitor/MonitorCenter.java#L128
you have an action authenticating the user. It sets a variable in the
session. This variable is read by the monitor authenticator.

So, injecting a random username would not let him access to denied
resource, as, the check happen on all incoming request.

Cheers,

Clement

**Comment by cescoffier** [comment]
I will update the documentation with the content of my previous comment,

**Comment by Kricket** [comment]
OK, thanks.
