### ISSUE TITLE
watch mode not working 

### ISSUE THREAD

**Issue by hboumedane** [wisdom-framework/wisdom#474]
Hi,

I'm on wisdom 0.8 and when running on watch mode the first time every thing work fine but if I modify some thing (template, java class, conf file) I got an exception 'no route found'.
I tried to access monitor to see if my bundles and components are OK and I saw that I don't have any services or ipojo component.
 I

**Comment by cescoffier** [comment]
You have to tell more about your projects. Probably a leak somewhere.

2015-04-21 10:10 GMT+02:00 hboumedane <notifications@github.com>:

**Comment by hboumedane** [comment]
what do you need to know ?

**Comment by cescoffier** [comment]
What kind of projects you are doing, which components are you using.

2015-04-21 10:30 GMT+02:00 hboumedane <notifications@github.com>:

**Comment by hboumedane** [comment]
it's web project, i'm bootstap,jquery, openjpa (three model) with datasource configured against postgresql. 
I'm using wisdom-datasources, wisdom-mailer .

**Comment by cescoffier** [comment]
so probably a leak in openjpa.

2015-04-21 10:35 GMT+02:00 hboumedane <notifications@github.com>:

**Comment by hboumedane** [comment]
maybe, but I and my colleague uses openjpa and they don't have this issue ???

**Comment by cescoffier** [comment]
I've seen once that many to many relations can be an issue. Do you have
such kind of relation ?

2015-04-21 10:39 GMT+02:00 hboumedane <notifications@github.com>:

**Comment by hboumedane** [comment]
no, i have only this : 
```
@OneToOne (cascade=CascadeType.ALL, fetch = FetchType.EAGER)
```

**Comment by cescoffier** [comment]
Can you provide a reproducer ?

**Comment by hboumedane** [comment]
what do you mean ? my project ?

**Comment by cescoffier** [comment]
No, a small projects to reproduce the issue, or the steps to reproduce it.

2015-04-21 16:48 GMT+02:00 hboumedane <notifications@github.com>:

**Comment by hboumedane** [comment]
here the steps to reproduce this : 
- have wisdom project 0.8.
- have datasource against postgresql 9.
- have wisdom-mailer
- have wisdom-opnjpa-enhancer

The issue happen when running on watch mode and trying to modify any file (controller, template, css, js)

**Comment by cescoffier** [comment]
Well, I've tried that and it works as expected.

2015-04-21 16:56 GMT+02:00 hboumedane <notifications@github.com>:

**Comment by hboumedane** [comment]
As I told you above, my colleague have similar projects wich include the same configuration and they don't have this issue !!!
so, why do I have this issue !! could it be an osgi issue ?

**Comment by cescoffier** [comment]
Yes, it a leak as I told you. The question is where is the leak, which
class / instance do not release everything.  My first guess would a a
static field. But cannot say without a reproducer.

2015-04-21 17:03 GMT+02:00 hboumedane <notifications@github.com>:

**Comment by hboumedane** [comment]
I Will see with Thomas and get back to you tommorrow

**Comment by hboumedane** [comment]
Can you tell me where to look ? how can debug this issue ??

**Comment by hboumedane** [comment]
How can I send you reproducer ?

**Comment by cescoffier** [comment]
@hboumdedane sent me a reproducer. Will have a look.

**Comment by cescoffier** [comment]
The reproducer does not reproduce the issue.

**Comment by cescoffier** [comment]
Close the issue as it cannot be reproduced.
