### ISSUE TITLE
Configure assets controller(s)

### ISSUE THREAD

**Issue by jbrey** [wisdom-framework/wisdom#475]
Hey,

It would be great if we could create several instances (via cfg files?) of the AssetController by giving the following properties:

- the path in the bundle or on file system,
- the alias on which the resources are published,
- if we manage assets from bundles.

Cheers
JB

**Comment by cescoffier** [comment]
Right now it's only possible to configure the 'external' asset directory (so from file system). We should add:

* the internal bundle directory (default to `assets`)
* the root path on which the resources are exported (default to `/assets`)

We should check that the resources exposed by these new configured instances are listed correctly on the `/assets/` page.

**Comment by jbrey** [comment]
Thanks !
