### ISSUE TITLE
WebJar watch mode does not work as expected

### ISSUE THREAD

**Issue by jbrey** [wisdom-framework/wisdom#479]
Hi,

I am testing the **webjar packaging** and **watch mode**. It seems wisdom does not behave as expected (at least the way I thought it behaves :) )

Here is the context:

- One **webjar module** with some js files, packaging wisdom / configuration packageWebJar=true
=> webjar is built correctly with a web jar classifier

- One **application module** which depends on the above webjar. Here I have an html file which uses the files located in the webjar

- wisdomDirectory of the webjar module is set to the target wisdom directory of the application module

Here are the steps:

1. I run mvn wisdom:run on the application
=> resources of the webjar modules are published on /libs/...
2. I run mvn wisdom:run on the webjar module (wisdomDirectory is set in the pom file directly)
=> all seems ok
=> in fact, now my **resources are published on /libs/... and /assets/...**
3. I update the resources in the webjar module
=> only the jar file is reloaded by the application and the /assets/... resources are updated
=> **webjar and /libs/... resources are not**

What do you think ?

Cheers
JB

**Comment by romainPellerin** [comment]
+1 I experience the same thing with ractivejs webjar from wisdom-ractive
plugin.

--




*Romain Pellerin | Founder - CEO*

1 rue Fleming - 17000 La Rochelle | www.ubidreams.com

Phone (France): +33 (0) 516 490 484 (office) |  +33 (0) 689 289 580
(mobile)

Phone (US): +1 (415) 680 4311 (mobile)


*Founder & Mentor NANOKO open source project *|  www.nanoko.org

Blog <http://romainpellerin.fr/>  | Linkedin
<http://www.linkedin.com/in/romainpellerin> | Google+
<http://plus.google.com/117099266649367147445/posts> | Twitter
<http://twitter.com/#!/rom1_ubidreams> | ID Skype: rom1_ubidreams

**Comment by cescoffier** [comment]
So, two actions here:

1. let specify that you want to copy only the webjar instead of the regular _bundle_
2. be sure it is updated in watch mode.

**Comment by jbrey** [comment]
In fact, I've figured out after, that it is specified (correctly IMO) in the package-webjar mojo description.

http://wisdom-framework.org/wisdom-maven-plugin/0.8.0/package-webjar-mojo.html#webjar

**Comment by cescoffier** [comment]
clearly a bug.

**Comment by cescoffier** [comment]
So several things:

1. Add a `deployBundleToWisdom` parameter to disable the deployment of the bundle
2. Add a `deployWebJarToWisdom` parameter to disable the deployment of the bundle
3. Fix the watch mode for webjar in order to redeploy them
