### ISSUE TITLE
Minify css files that are results of less compilation

### ISSUE THREAD

**Issue by jbrey** [wisdom-framework/wisdom#482]
Hi,

When I use Less as source files, the output css are not minified.

JB

**Comment by cescoffier** [comment]
It should also work for Myth compilation too. So every new css generated in `target/classes` should be minified.

**Comment by jbrey** [comment]
I think that if you follow what is defined right now on sources folder, it should only minify target/classes/assets.

**Comment by cescoffier** [comment]
So actually it is working when an aggregation is specified (this is definitely not convenient). 
I'm adding the direct support.
