### ISSUE TITLE
RAML - Issue when a controller does not have a @Path with a value 

### ISSUE THREAD

**Issue by jetien** [wisdom-framework/wisdom#484]
Hi,
I just add the wisdom-raml extension to projet (plugin and monitor extension) but it seems that the template returned does not load correctly (there is an infinite loader) and the controller.raml returned by the server is not displayed.
Show it on the attached screenshot

![wisdom-raml_bug](https://cloud.githubusercontent.com/assets/2607347/7316073/f0bd0a08-ea73-11e4-9f25-2f84010356d7.png)

**Comment by barjo** [comment]
It seems that it freeze because of the "null" parents root. I guess it happens if @path is not specified on the controller. Definitely a bug! Thanks (^^)b

**Comment by jetien** [comment]
I just test with default @Path on controller but it seems to be the same...

![capture d ecran 2015-04-24 a 12 23 56](https://cloud.githubusercontent.com/assets/2607347/7317080/eb9665ac-ea7c-11e4-95f0-f7ace6e3d9f3.png)

**Comment by barjo** [comment]
I just push a fix that should solve the problem. It needed @Path with a value, now in case there is no value or no @parh I put / by default

**Comment by cescoffier** [comment]
I've renamed the issue.

**Comment by barjo** [comment]
@jetien seems there is an other problem in addition to the path, I am not sure exactly why the api-console have problem. Can you try to put a small comment before the @author tag in the TestController class javadoc. The @author may mess up there js parser, am not sure but that worth a try.

**Comment by barjo** [comment]
I try with the @author, that does pause problem :-?

**Comment by barjo** [comment]
@jetien Ah, one last thing, if you have fix the base url, can you put it to http://localhost:9000/ with the '/' at the end. That may be the issue here.

**Comment by barjo** [comment]
Actually, that should be alright since the path of your controller will be appended to the base url, but I can see in your raml file, that it didn't occured. I will try to reproduce

**Comment by barjo** [comment]
Ah I reproduce it. It is still linked to the Controller '@path' annotation. It must start with a '/'

**Comment by cescoffier** [comment]
Any fix ?

**Comment by barjo** [comment]
https://github.com/wisdom-framework/wisdom/commit/bb42eb9797b77d4a0a805051f4f2b0ff2244f12e fix the missing `@Path` issue.

**Comment by barjo** [comment]
@jetien I create an other issue related to the infinite loading -> #487

**Comment by jetien** [comment]
Hi,

ok thanks I'll try it just now

2015-04-26 14:57 GMT+02:00 Jonathan Bardin <notifications@github.com>:

> @jetien <https://github.com/jetien> I create an other issue related to
> the infinite loading -> #487
> <https://github.com/wisdom-framework/wisdom/issues/487>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wisdom-framework/wisdom/issues/484#issuecomment-96374911>
> .
>



-- 

Julien ETIEN | Ingénieur Etudes et Développement
1 rue Fleming - Bureau 11 - 17000 La Rochelle
*+33 (0)5 16 49 04 84 | +33 (0)6 07 88 76 72*
website : www.ubidreams.com
Skype : julien.etien
