### ISSUE TITLE
JacksonSingleton should not force FAIL_ON_UNKNOWN_PROPERTIES on us

### ISSUE THREAD

**Issue by magnet** [wisdom-framework/wisdom#486]
```
    private void setMappers(ObjectMapper mapper, XmlMapper xml) {
        synchronized (lock) {
            this.mapper = mapper;
            this.xml = xml;
            if (mapper != null) {
                this.mapper.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
            }
            if (xml != null) {
                this.xml.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
            }
        }
    }
```

I'd argue to keep Jackson's own defaults and have a configuration option to set extra deserialization/serialization features.

I understand being lenient might look like a better default for some applications, and that there might be existing Wisdom projects that now rely on that default. But it's not a sensible default, and it should at least be possible to disable this setting in the configuration.

(as an argument on why Wisdom shouldn't redefine Jackson's defaults: we just spent one hour determining why exactly Jackson was behaving differently between our Wisdom routes and our unit tests).

**Comment by cescoffier** [comment]
Oh I see the issue. 
However it's a recommended default to support evolution. So, let's add a configuration option to disable this default.

**Comment by cescoffier** [comment]
Let's have a `jackson` configuration to enable / disable any of the Jackson feature. IF not set, it would use current default. If set, it applied the configuration.

**Comment by magnet** [comment]
Thanks :)
