### ISSUE TITLE
Expose the ability to set the input delimiter in javascript compiler mojo

### ISSUE THREAD

**Issue by jbrey** [wisdom-framework/wisdom#493]
Hi,

Would it be possible to expose the configuration of the PrintInputDelimiter of google closure ?

Indeed today, when we aggregate files without minifying them, the output files contains the **absolute path** of the files that have been aggregated.

NB: L. 179 of JavaScriptCompilerMojo.java: options.setInputDelimiter("// -- File: %name% ( Input %num% ) -- // ");

PS: maybe more configuration of google closure could be exposed...

Cheers
JB

**Comment by cescoffier** [comment]
@barjo - you have added this feature, could you check ?

**Comment by barjo** [comment]
Ok I will have a look at it :+1:

**Comment by barjo** [comment]
I just commit, you can now set the delimiter explicitly via the mojo parameter `googleClosureInputDelimiter`

**Comment by jbrey** [comment]
Thanks. I'll try it soon.

Cheers
JB
