### ISSUE TITLE
Json received in POST HTTP request cut

### ISSUE THREAD

**Issue by PierrickTact** [wisdom-framework/wisdom#503]
Hi,

I try to receive heavyweight json in this specific route : 
@Route(method = HttpMethod.POST, uri= "/heavyweightReport")
public Result storeHeavyweightReport( @NotNull @Body HeavyweighReport heavyweighReport) {
  //some code
}

My object HeavyweighReport contains 3 elements : 
    - private String data1;
    - private String data2;
    - private List<String> dataList;

It works fine for requests with less than ~2716 elements in data list , but with more than ~2716 elements (around 108707 characteres) in this report, the json recieved is cut.

I try to send this Json with several solutions (with content-length or chunked parameters in the request) but I have the same problem.

I tried to define my own Json serializer/deserializer but the json recieved by the parser is already cut.

I already used an other heavyweigh report without list content and it works fine, have we got a size limitation for list content ? Or did I do something wrong ?

I use :
    - wisdom : 0.8.0
    - java : 1.8
    - OS : ubuntu 14.04

**Comment by cescoffier** [comment]
Hi,

This is "normal" I guess ;-)

Configure the "request.body.max.size" property to increase the size. The
body size is limited to avoid size attacks. By default the value is 102400.

Cheers,

Clement

2015-05-13 10:47 GMT+02:00 PierrickTact <notifications@github.com>:

**Comment by PierrickTact** [comment]
It works !

Thanks so much for your reactivity  !
