### ISSUE TITLE
Multiple layout resolution is not guarantee

### ISSUE THREAD

**Issue by kevinsdooapp** [wisdom-framework/wisdom#506]
Considering multiple modules with different layout. For exemple:
templates/customers/customer_layout.thl.html
template/customers/profile.thl.html
```
<html layout:decorator="customer_layout">
...
</html>
```
templates/users/layout.thl.html
templates/users/profile.thl.html
```
<html layout:decorator="layout">
...
</html>
```

ie. Wisdom monitor module also define a layout.thl.html layout in the templates/monitor folder.

The wisdom monitor module sometimes replace the other layouts. The consequence is that profile.thl.html get the monitor sidebar instead of the right layout in the right folder.

In my opinion, it should be a layouts resolution problem. If I stopped the wisdom monitor module, the layout of the users/profile page is now the customers/customer_layout :confused: 

Wisdom 0.9.1

**Comment by cescoffier** [comment]
Hi,

This is a bug, definitely. Looks like Thymeleaf template resolution looks for any template called 'layout' without enforcing the path. 

Looking into it.

**Comment by cescoffier** [comment]
The template resolver does not handle the 'relative' layout correctly.

**Comment by kevinsdooapp** [comment]
Hi @cescoffier,
Nice to know it's resolved! Did you notice that the problem is also present for static pages resolution?
I tried to define a index.html in assets and then I redirected to it in the controller and it loaded the index.html page of the wisdom documentation :confused: 
I don't know if this fix solve it yet.
```
    @Route(method = HttpMethod.GET, uri = "/")
    public Result index() {
       return redirect("/assets/index.html");
    }
```

**Comment by Rizen59** [comment]
Hi @cescoffier, @kevinsdooapp 
I got exactly the same issue in 0.10.0-SNAPSHOT trying to display the dashboard view in the monitor. Thymeleaf was trying to processed a template that it should not, whatever the sub-directory it's included, in your example "customer_layout.thl.html"

After some research in debug mode here is what happened:

After that wisdom and thymeleaf were processed the content of dashboard.thl.html they continue with the defined decorator, in the dashboard template it's "layout".

```html
<!-- Start of file dashboard.thl.html included in the wisdom-monitor module -->
<!DOCTYPE html>
<html layout:decorator="layout">
<head lang="en">
<!-- More code here... -->
```

To find the file associated to "layout" wisdom will call the following method in **ThymeleafTemplateCollector** class.

```java
    public ThymeLeafTemplateImplementation getTemplateByResourceName(String resourceName) {
        Collection<ThymeLeafTemplateImplementation> list = registrations.keySet();
        for (ThymeLeafTemplateImplementation template : list) {
            if (template.fullName().endsWith(resourceName)
                    || template.fullName().endsWith(resourceName + "." + extension())) {
                return template;
            }
            // more code here
        }
        return null;
    }
```

Here are the variables at this moment :
- resourceName ---> "layout" 
- registrations ---> contains every known template whatever the sub-directory. So in your case it will include "customer_layout.thl.html".
- template.fullName() ---> somethings like this "bundle://55.0:0/templates/customer_layout.thl.html"

So the line `template.fullName().endsWith(resourceName + "." + extension())` will return true and customer_layout will be processed. This is not what we want ^^

What it should be done here is to parse *template.fullName()*, then test with equals the resourceName.
