### ISSUE TITLE
Is it possible to switch vertx engine on 3.0.0 version?

### ISSUE THREAD

**Issue by mxmind** [wisdom-framework/wisdom#527]
The vertx 3.0.0 is stable release now. Wold be great to update vertx engine to this version. If it possible to add support of rx version, that will be really awesome.

**Comment by barjo** [comment]
Hi, I will see what I can do :)

**Comment by barjo** [comment]
Unfortunately, vertx-platform 3.0.0 has not yet been released, we will move to vertx 3.0.0 when so.

**Comment by cescoffier** [comment]
Well, vertx-platform does not exist anymore, you just need vertx core. 

Vert.x Core is an OSGi bundle, so the engine can be implemented on top of it. It's a low level API as the one used Today. The threading model is a bit different, so we may need to modify the AsynInputStream. 

The Hazelcast cluster manager is not an OSGi bundle, so should be packaged. unlike vert.x 2, vert.x 3 let you inject your own cluster manager, meaning we can deliver it separately and inject it as a service. Even if hazelcast is the only officially supporter cluster manager, 2 others are going to be supported soon (JGroup and Zookeeper). 

That's to get the same state as we have right now.

But, my idea is to also integrate vert.x web and remove lots of code of wisdom to rely on the vert.x web features (CORS, OAuth, Cookie implementation...).

In addition, it should be possible to deploy vert.x verticle as OSGi bundles as shown here https://github.com/vert-x3/vertx-examples/tree/master/osgi-examples

**Comment by barjo** [comment]
Thanks for the update! That's quite few nice change.

**Comment by cescoffier** [comment]
A first version relying on vertx-core 3.1.0 should be available soon.

**Comment by mxmind** [comment]
Excellent, good news!!!
10 жовт. 2015 11:22 дп "Clement Escoffier" <notifications@github.com> пише:

**Comment by cescoffier** [comment]
Fixed in master, it used vertx-core 3.1.0. More work in coming....
