### ISSUE TITLE
Bug : Synchronization between wisdom monitor and iCasa platform

### ISSUE THREAD

**Issue by GerbertGaillard-Eva** [wisdom-framework/wisdom#529]
Hello,

I was trying to visualize iPOJO instances form iCasa platform with wisdom monitor 0.8.0,
but the information displayed wasn't the right one : 
it was information from the previous launched platform that I exited.
Information displayed isn't corresponding to the last platform launched even if I refresh the web page and re-log.

**Comment by cescoffier** [comment]
Well, it's not an issue of Wisdom, but from iCASA or whatever system manage the synchronization.

Wisdom Monitor is delegating to iPOJO to get the instances. It's obviously in sync with the current configuration.
