### ISSUE TITLE
Wisdom build

### ISSUE THREAD

**Issue by remi-parain** [wisdom-framework/wisdom#533]
The build fail when processing the **extensions**. It seems that some artifact have dependency to wisdom documentation 0.10.0-SNAPSHOT which isn't built yet ( according to the build order of the README).
Building **documentation** before **extension** revolve the issue

```text
[INFO] Reactor Summary:
[INFO] 
[INFO] wisdom-framework-project ........................... SUCCESS [  2.771 s]
[INFO] wisdom-markdown-maven-plugin ....................... SUCCESS [ 22.533 s]
[INFO] wisdom-npm-runner-maven-plugin ..................... SUCCESS [  6.485 s]
[INFO] wisdom-asciidoc-maven-plugin ....................... SUCCESS [  8.934 s]
[INFO] wisdom-monitor ..................................... SUCCESS [ 19.064 s]
[INFO] wisdom-filters ..................................... SUCCESS [  7.501 s]
[INFO] Archetype - wisdom-default-project-archetype ....... FAILURE [ 36.657 s]
[INFO] Archetype - wisdom-simple-watcher-archetype ........ SKIPPED
[INFO] wisdom-raml ........................................ SKIPPED
[INFO] wisdom-source-model ................................ SKIPPED
[INFO] wisdom-raml-maven-plugin ........................... SKIPPED
[INFO] wisdom-raml-monitor-console ........................ SKIPPED
[INFO] wisdom-instantiatedBy .............................. SKIPPED
```
from **wisdom/extensions/wisdom-default-project-archetype/target/it/projects/default/acme-sample/build.log** :

```text
[ERROR] Failed to execute goal on project acme-sample: Could not resolve dependencies for project org.acme:acme-sample:wisdom:1.0-SNAPSHOT: Could not find artifact org.wisdom-framework:documentation:jar:0.10.0-SNAPSHOT -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project acme-sample: Could not resolve dependencies for project org.acme:acme-sample:wisdom:1.0-SNAPSHOT: Could not find artifact org.wisdom-framework:documentation:jar:0.10.0-SNAPSHOT
```

**Comment by cescoffier** [comment]
Definitely, my fault. I’ve added the monitor to documentation/sample. It changes the resolution order. Will fix this.

Thanks for reporting !

On 14 octobre 2015 at 10:48:24, Rémi Parain (notifications@github.com) wrote:

The build fail when processing the extensions. It seems that some artifact have dependency to wisdom documentation 0.10.0-SNAPSHOT which isn't built yet ( according to the build order of the README).
Building documentation before extension revolve the issue

[INFO] Reactor Summary:
[INFO]  
[INFO] wisdom-framework-project ........................... SUCCESS [  2.771 s]
[INFO] wisdom-markdown-maven-plugin ....................... SUCCESS [ 22.533 s]
[INFO] wisdom-npm-runner-maven-plugin ..................... SUCCESS [  6.485 s]
[INFO] wisdom-asciidoc-maven-plugin ....................... SUCCESS [  8.934 s]
[INFO] wisdom-monitor ..................................... SUCCESS [ 19.064 s]
[INFO] wisdom-filters ..................................... SUCCESS [  7.501 s]
[INFO] Archetype - wisdom-default-project-archetype ....... FAILURE [ 36.657 s]
[INFO] Archetype - wisdom-simple-watcher-archetype ........ SKIPPED
[INFO] wisdom-raml ........................................ SKIPPED
[INFO] wisdom-source-model ................................ SKIPPED
[INFO] wisdom-raml-maven-plugin ........................... SKIPPED
[INFO] wisdom-raml-monitor-console ........................ SKIPPED
[INFO] wisdom-instantiatedBy .............................. SKIPPED

from wisdom/extensions/wisdom-default-project-archetype/target/it/projects/default/acme-sample/build.log :

[ERROR] Failed to execute goal on project acme-sample: Could not resolve dependencies for project org.acme:acme-sample:wisdom:1.0-SNAPSHOT: Could not find artifact org.wisdom-framework:documentation:jar:0.10.0-SNAPSHOT -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project acme-sample: Could not resolve dependencies for project org.acme:acme-sample:wisdom:1.0-SNAPSHOT: Could not find artifact org.wisdom-framework:documentation:jar:0.10.0-SNAPSHOT
