### ISSUE TITLE
Request body truncated when it exceed "request.body.max.size"

### ISSUE THREAD

**Issue by nicolas-rempulski** [wisdom-framework/wisdom#535]
I ran into an issue regarding requests body size.

Due to [request.body.max.size](https://github.com/wisdom-framework/wisdom/blob/d7656365cf5ff9a72cb6dfaea9a25345036e5a54/core/wisdom-vertx-engine/src/main/java/org/wisdom/framework/vertx/RequestFromVertx.java#L105) Wisdom may receive a truncated request. 
If the request body size exceed this threshold, extra content is discarded and the request is still handled by Wisdom as everything went fine.

I think if the request exceed the body size limit, Wisdom should immediatly return a Bad Request "Body size exceeding configuration limit" or throw some kind of exception.

**Comment by cescoffier** [comment]
I think a "413 - Body size exceeded" message would be ok. (yes there is a status code for this).
