### ISSUE TITLE
Configuration injected while .conf file not entirely parsed

### ISSUE THREAD

**Issue by nicolas-rempulski** [wisdom-framework/wisdom#536]
I am not sure it is really an issue. 

I initialize some of my components with a @Validate method. In this method I request some value from the configuration file.

I am banging my head with strange behaviors where, most of the time, I retrieve the default value while the configuration file contain another value for the specified key.

When I log the content of Configuration service with asMap().toString() I have different values at each startup.

I worked around this by retrieving the value when it is first needed (long after the startup) but I am wondering if there is an issue with using @Validate to initialize configuration value or if there is an issue with Configuration publishing its service while its not yet ready.

**Comment by cescoffier** [comment]
Looks like a bug. The `Configuration` service should not be published until the full configuration is read.

**Comment by nicolas-rempulski** [comment]
Here is a reproducer : https://github.com/nicolas-rempulski/536-reproducer

Config map size and content is diplayed at startup and when GET / is called.

It doesn't seems to be an injection timing problem. 
Indeed the config size returned by the @Validate method is the same that the one returned later by the Route. I thought it could be a serialization problem with asMap, but the monitor6.value shows that its the default value that is used and not "yoyoyo" as specified in the configuration file.

**Comment by nicolas-rempulski** [comment]
Mea culpa !

I used @Requires Configuration insteal of @Requires ApplicationConfiguration. Thus a random Configuration was injected ... often not the right one.

Everything works fine once this is corrected (thx Clément !)
