### ISSUE TITLE
@Body Annotation is always empty by POST of a form

### ISSUE THREAD

**Issue by HardyLoppmann** [wisdom-framework/wisdom#538]
I tried to program a small example application with a form and a submit. It´s impressed from these examples:
* https://github.com/thymeleaf/thymeleafsandbox-springjsp.git
* https://github.com/wisdom-framework/wisdom-jdbc

But I have the problem, the ```@Body``` in the POST-method is always empty, I have committed the small program here: git@github.com:HardyLoppmann/form.git so you can take a look.

I don´t know, it is a bug or I´m going the wrong way ...

I use Java 1.8.0_60 on OS X

**Comment by cescoffier** [comment]
Just a guess,

did you try with a template like this one:
https://github.com/wisdom-framework/wisdom/blob/master/documentation/samples/src/main/resources/templates/hello/index.thl.html#L39

**Comment by HardyLoppmann** [comment]
with some impressions from the example above it´s ok, https://github.com/HardyLoppmann/form.git
