### ISSUE TITLE
Upgrade apache felix version to support java 8u66

### ISSUE THREAD

**Issue by kevinsdooapp** [wisdom-framework/wisdom#545]
The current version of apache felix used by wisdom is not compatible with java 8u66. (Unable to resolve com.sun.jna).

It works with apache felix framework 5.4.0.

**Comment by cescoffier** [comment]
It requires an update in chameleon first.

**Comment by cescoffier** [comment]
I've opened an issue on Chameleon: https://github.com/ow2-chameleon/core/issues/48
