### ISSUE TITLE
Problem with RequestRouter#FilterSet Imutable iterator and Collections.sort with guava 19

### ISSUE THREAD

**Issue by barjo** [wisdom-framework/wisdom#550]
Guava 19 will throw an `com.google.common.collect.UnmodifiableListIterator.set` when https://github.com/wisdom-framework/wisdom/blob/master/core/router/src/main/java/org/wisdom/router/RequestRouter.java#L489 is called. ` ImmutableList.copyOf(this).iterator();` return an  `UnmodifiableListIterator`

**Comment by cescoffier** [comment]
I'm not sure I follow. 

It creates an unmodifiable list taking a snapshot of the current list. This should not be used to modify the underlying list (that's the purpose). 

Do you have a reproducer for this issue ?

**Comment by barjo** [comment]
Am not sure from where it comes, but the bindFilter, will add a filter that throw an `UnmodifiableListIterator` from guava 19 when sorted . I got it with a 0.10.0-SNAPSHOT wisdom framework.

**Comment by cescoffier** [comment]
It's because of the sort implementation sorting an array but setting the values using a ListIterator.

**Comment by barjo** [comment]
tricky

**Comment by barjo** [comment]
side question, would it makes sens to use a TreeSet to store the filter rather than an ArrayList?

**Comment by cescoffier** [comment]
I've attempted a fix, please let me know as I'm unable to reproduce it.

**Comment by jetien** [comment]
It works for me ! thks

**Comment by barjo** [comment]
That works for me too (^^)b
