### ISSUE TITLE
Multiple SockJS prefixes triggered a periodic vertx log warn

### ISSUE THREAD

**Issue by aygalinc** [wisdom-framework/wisdom#557]
If i provide multiple prefixes in the application.conf , vertx log a periodic warn message : 
[WARN]	 o.v.j.c.s.i.DefaultSockJSServer {vert.x-eventloop-thread-2} - You have overwritten the Http server request handler AFTER the SockJSServer has been created which will stop the SockJSServer from functioning. Make sure you set http request handler BEFORE you create the SockJSServer 

I don't know if it can be an issue because the sockJS communication works perfectly fine, but the wisdom console is full of this trace.

Regards,

**Comment by cescoffier** [comment]
Were you able to find the source of the issue (never saw it before)

**Comment by aygalinc** [comment]
Not know, i will check when i have more time.

**Comment by aygalinc** [comment]
The issue was present in wisdom 0.9.1 but disappear in wisdom 0.10.0-SNAPSHOT.

Maybe linked to vertx version.
