### ISSUE TITLE
Suggestion: Show requests and execution time in monitoring

### ISSUE THREAD

**Issue by kevinsdooapp** [wisdom-framework/wisdom#558]
Hi,

Could be nice to display in monitor interface, the requests by route ordered by their execution time in order to identify possible problems (missing indexes, missing @Async...)

If nobody have time to do it, it'll take the time when I'll be less busy ;)

**Comment by cescoffier** [comment]
👍

**Comment by kevinsdooapp** [comment]
You can find an implementation of this extension here ;)
[https://github.com/dooApp/wisdom-extensions/tree/develop/wisdom-requests-monitor](https://github.com/dooApp/wisdom-extensions/tree/develop/wisdom-requests-monitor)
