### ISSUE TITLE
Make a non-static version of the Results#status method

### ISSUE THREAD

**Issue by Riduidel** [wisdom-framework/wisdom#563]
In order to implement HATEOAS controller with style, I would like to have a non static version of the `Results#status` method. This way, I would be able, through annotation on controller method and overwriting of the `Result` class, able to inject links in returned JSON values.

**Comment by Riduidel** [comment]
Not yet sure if it's the best way. I must first think a little more about that HATEOS thingie.

**Comment by cescoffier** [comment]
Can't use use an interceptor for this ?
